#!/usr/bin/env python
#
# Script to build the files found in this directory.
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper(env);
rootlibs  = env['ROOTLIBS']

mainlib = helper.make_mainlib ( [ ] )

helper.make_plugins( [ mainlib,
                       'art_Framework_Core',
                       'art_Framework_Principal',
                       'art_Persistency_Common',
                       'art_Persistency_Provenance',
                       'art_Framework_Services_Registry',
                       'art_root_io_tfile_support',
                       'art_root_io_TFileService',
                       'art_Utilities',
                       'canvas',
                       'fhiclcpp',
                       'fhiclcpp_types',
                       'tbb',
                       'cetlib',
                       'cetlib_except',
                       'boost_filesystem',
                       'Core',
                       rootlibs,
                     ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
